
model_params:
    sh_degree: 2
    flow_loss_type: 'warp'
    flow_batch: 16
    flow_scale: 0.8
    update_mask: "viewspace_diff"
    update_loss: "mse"
    gaussian_update_thresh: 1.0e-3
    pixel_update_thresh: 0.001
    dilate_size: 48
    depth_init: True
    depth_thresh: 0.1
    adaptive_render: True
    adaptive_update_period: 0.3
    max_frames: 300
    seed: 0

    gate_temp: 0.3
    gate_gamma: -0.5
    gate_eta: 1.01
    gate_lr: 0.1
    gate_lambda_l2: 0.0
    gate_lambda_l0: 0.01

    lambda_depth: 0.0
    lambda_depthssim: 0.3
    depth_pix_range: 20
    depth_num_comp: 3
    depth_tolerance: 0.01
    depth_pair_int: 300
    depth_from_iter: 4000
    depth_until_iter: 10000

    # fill these in for your wandb logging
    wandb_project: ''
    wandb_entity: ''
    wandb_log_error_maps: True
    wandb_log_error_map_frames: 300 # log error maps for all 300 frames in dynerf sequences
    wandb_error_map_vmin: 0.0
    wandb_error_map_vmax: 0.4 # all errors above 0.4 are clamped to red
    wandb_error_map_cmap: "jet"
    wandb_tags: 'default'
    use_wandb: False

quantize_params:
    xyz_quant_type: 'none'
    xyz_gate_params: 'on'

    f_rest_quant_type: 'sq'
    f_rest_latent_dim: 4
    f_rest_latent_scale_norm: 'none'
    f_rest_ldecode_matrix: 'learnable'
    f_rest_ldec_std: 1.0e-1

    f_dc_quant_type: 'sq_res'
    f_dc_latent_dim: 8
    f_dc_latent_scale_norm: 'none'
    f_dc_ldecode_matrix: 'learnable'
    f_dc_ldec_std: 1.0e-4

    rot_quant_type: 'sq_res'
    rot_latent_dim: 6
    rot_latent_scale_norm: 'none'
    rot_ldecode_matrix: 'learnable'
    rot_ldec_std: 1.0e-2

    op_quant_type: 'sq_res'
    op_latent_dim: 3
    op_latent_scale_norm: 'none'
    op_ldecode_matrix: 'dft'
    op_ldec_std: 1.0e-4

    sc_quant_type: 'sq_res'
    sc_latent_dim: 8
    sc_latent_scale_norm: 'none'
    sc_ldecode_matrix: 'learnable'
    sc_ldec_std: 1.0e-3

opt_params_initial:
    epochs: 500
    opacity_reset_interval: 600
    densify_until_epoch: 0.8
    densify_grad_threshold: 0.0003
    position_lr_max_steps: 12000
    f_rest_ldecs_lr: 1.0e-3
    f_rest_lr_scaling: 5.0
    lambda_flow: 0.0
    lambda_tv: 0.1


opt_params_rest:
    epochs_rest: 10

    xyz_ldecs_lr_rest: 1.0e-3
    xyz_lr_scaling_rest: 10.0
    position_lr_init_rest: 0.0005
    
    f_dc_ldecs_lr_rest: 1.0e-3
    f_dc_lr_scaling_rest: 5.0
    features_dc_lr_rest: 0.0025

    rot_ldecs_lr_rest: 1.0e-3
    rot_lr_scaling_rest: 0.5
    rotation_lr_rest: 0.05

    op_ldecs_lr_rest: 1.0e-4
    op_lr_scaling_rest: 1.0

    sc_ldecs_lr_rest: 1.0e-4
    sc_lr_scaling_rest: 1.0
    scaling_lr_rest: 0.01

    lambda_flow_rest: 0.0
    lambda_tv_rest: 0.1

    densify_until_epoch_rest: 0.8
    densification_interval_rest: 2
    densify_grad_threshold_rest: 0.00125
    calc_dense_stats_rest: 4
    percent_dense_rest: 0.01
    min_opacity_rest: 0.01
    size_threshold_rest: 20